### ISSUE TITLE
Error when trying to open nautilus

### ISSUE THREAD

**Issue by ruizlenato** [DorianRudolph/sirula#20]
Log:
```
thread 'main' panicked at 'Error while launching app: Error { domain: g-dbus-error-quark, code: 4, message: "Message recipient disconnected from message bus without replying" }', src/util.rs:102:49
stack backtrace:
   0:     0x56497bda096d - <unknown>
   1:     0x56497bd02c0c - <unknown>
   2:     0x56497bd9ff94 - <unknown>
   3:     0x56497bd9fc7b - <unknown>
   4:     0x56497bdca918 - <unknown>
   5:     0x56497bdca896 - <unknown>
   6:     0x56497bdca852 - <unknown>
   7:     0x56497bcd6e00 - <unknown>
   8:     0x56497bcd70e2 - <unknown>
   9:     0x56497bd983b2 - <unknown>
  10:     0x56497bd9dc87 - <unknown>
  11:     0x7f1239eb889f - g_cclosure_marshal_VOID__OBJECTv
  12:     0x7f1239ed7c96 - g_signal_emit_valist
  13:     0x7f1239ed7e04 - g_signal_emit
  14:     0x7f123a56c6fb - <unknown>
  15:     0x7f123a42428b - <unknown>
  16:     0x7f1239ed7c96 - g_signal_emit_valist
  17:     0x7f1239ed7e04 - g_signal_emit
  18:     0x7f123a52dffd - <unknown>
  19:     0x7f1239ebe680 - g_cclosure_marshal_VOID__BOXEDv
  20:     0x7f1239ed7c96 - g_signal_emit_valist
  21:     0x7f1239ed7e04 - g_signal_emit
  22:     0x7f123a5255e8 - <unknown>
  23:     0x7f123a52d80b - <unknown>
  24:     0x7f123a52e444 - <unknown>
  25:     0x7f123a4f4273 - gtk_event_controller_handle_event
  26:     0x7f123a6c7b5f - <unknown>
  27:     0x7f123a4229e5 - <unknown>
  28:     0x7f1239ed7c96 - g_signal_emit_valist
  29:     0x7f1239ed7e04 - g_signal_emit
  30:     0x7f123a6d6c45 - <unknown>
  31:     0x7f123a577a85 - <unknown>
  32:     0x7f123a5789a3 - gtk_main_do_event
  33:     0x7f123a2e1643 - <unknown>
  34:     0x7f123a30eff4 - <unknown>
  35:     0x7f1239dbffd3 - g_main_context_dispatch
  36:     0x7f1239e16049 - <unknown>
  37:     0x7f1239dbd545 - g_main_context_iteration
  38:     0x7f1239fdd6ee - g_application_run
  39:     0x56497bd885b5 - <unknown>
  40:     0x56497bd9d973 - <unknown>
  41:     0x56497bd874ad - <unknown>
  42:     0x7f1239b81b25 - __libc_start_main
  43:     0x56497bcdf9de - <unknown>
  44:                0x0 - <unknown>
```

**Comment by DorianRudolph** [comment]
I cannot reproduce this. Could you add some more information about your setup? Does the same error happen with other gnome apps?

**Comment by pierrechevalier83** [comment]
I observe this as well.
I'm running `sway` on `Arch Linux`, and I get a panick when trying to launch `nautilus` or `gnome-chess`, so presumably any `gnome` program.

Here is a more detailed stack trace:
```
❯ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/sirula`
thread 'main' panicked at 'Error while launching app: Error { domain: g-dbus-error-quark, code: 4, message: "Message recipient disconnected from message bus without replying" }', src/util.rs:102:49
stack backtrace:
   0:     0x55a19438eb2c - std::backtrace_rs::backtrace::libunwind::trace::hb94371ae5f36cf60
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a19438eb2c - std::backtrace_rs::backtrace::trace_unsynchronized::hf2fab28b020fc4f0
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a19438eb2c - std::sys_common::backtrace::_print_fmt::hc03e7351fc1eba0e
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a19438eb2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ac055b69ddcc00b
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a1943b229c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/fmt/mod.rs:1149:17
   5:     0x55a19438bce5 - std::io::Write::write_fmt::h06fe7d6a5c3c6fd6
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/io/mod.rs:1697:15
   6:     0x55a194390360 - std::sys_common::backtrace::_print::hff27315094b787f3
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a194390360 - std::sys_common::backtrace::print::ha155a30d8ce78665
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a194390360 - std::panicking::default_hook::{{closure}}::h735ca8269f3d457c
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:211:50
   9:     0x55a19438ff0b - std::panicking::default_hook::h382660fc392a8939
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:228:9
  10:     0x55a194390a14 - std::panicking::rust_panic_with_hook::h7c0aca83ffce0d31
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:606:17
  11:     0x55a1943904f0 - std::panicking::begin_panic_handler::{{closure}}::h2d9f3917e56e3c37
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:502:13
  12:     0x55a19438efe4 - std::sys_common::backtrace::__rust_end_short_backtrace::hb2740127084ae930
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55a194390459 - rust_begin_unwind
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:498:5
  14:     0x55a19407e461 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:107:14
  15:     0x55a19407e553 - core::result::unwrap_failed::h885d3f7beb571353
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1613:5
  16:     0x55a1940a035b - core::result::Result<T,E>::expect::hc45f5c30edfd6b11
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1255:23
  17:     0x55a19408ed34 - sirula::util::launch_app::ha0532161d04b1e02
                               at /home/pierrec/Documents/code/sirula/src/util.rs:102:9
  18:     0x55a19408cb41 - sirula::app_startup::{{closure}}::hee06aeb24e266833
                               at /home/pierrec/Documents/code/sirula/src/main.rs:155:13
  19:     0x55a19408ab60 - <O as gtk::auto::list_box::ListBoxExt>::connect_row_activated::row_activated_trampoline::h8f95e96d62c89ce4
                               at /home/pierrec/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.14.3/src/auto/list_box.rs:1017:13
  20:     0x7f6a648a889f - g_cclosure_marshal_VOID__OBJECTv
  21:     0x7f6a648c7c96 - g_signal_emit_valist
  22:     0x7f6a648c7e04 - g_signal_emit
  23:     0x7f6a648c7c96 - g_signal_emit_valist
  24:     0x7f6a648c7e04 - g_signal_emit
  25:     0x7f6a650b31b5 - gtk_widget_activate
  26:     0x55a19409b17e - <O as gtk::auto::widget::WidgetExt>::activate::h0598c25a65badb68
                               at /home/pierrec/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.14.3/src/auto/widget.rs:1351:28
  27:     0x55a19408c951 - sirula::app_startup::{{closure}}::hf4322fe27d563fae
                               at /home/pierrec/Documents/code/sirula/src/main.rs:145:13
  28:     0x55a1940c07e9 - <O as gtk::auto::entry::EntryExt>::connect_activate::activate_trampoline::hb2828fcfefd63ac7
                               at /home/pierrec/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.14.3/src/auto/entry.rs:2601:13
  29:     0x7f6a648a9ebf - g_closure_invoke
  30:     0x7f6a648c6188 - <unknown>
  31:     0x7f6a64e3d555 - <unknown>
  32:     0x7f6a64e3da28 - <unknown>
  33:     0x7f6a64e3f5e2 - <unknown>
  34:     0x7f6a64e3f887 - gtk_bindings_activate_event
  35:     0x7f6a64ed18d9 - <unknown>
  36:     0x7f6a64e129e5 - <unknown>
  37:     0x7f6a648c718c - g_signal_emit_valist
  38:     0x7f6a648c7e04 - g_signal_emit
  39:     0x7f6a650c6c45 - <unknown>
  40:     0x7f6a650d55cc - gtk_window_propagate_key_event
  41:     0x7f6a650d7c2c - <unknown>
  42:     0x7f6a64e0ff38 - <unknown>
  43:     0x7f6a648a9ebf - g_closure_invoke
  44:     0x7f6a648c5b5e - <unknown>
  45:     0x7f6a648c7598 - g_signal_emit_valist
  46:     0x7f6a648c7e04 - g_signal_emit
  47:     0x7f6a650c6c45 - <unknown>
  48:     0x7f6a64f67b52 - <unknown>
  49:     0x7f6a64f689a3 - gtk_main_do_event
  50:     0x7f6a64cd1643 - <unknown>
  51:     0x7f6a64cfeff4 - <unknown>
  52:     0x7f6a647aff13 - g_main_context_dispatch
  53:     0x7f6a648060d9 - <unknown>
  54:     0x7f6a647ad485 - g_main_context_iteration
  55:     0x7f6a649cd6ee - g_application_run
  56:     0x55a1940a3c17 - <O as gio::application::ApplicationExtManual>::run_with_args::hd61595ef91db7457
                               at /home/pierrec/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.14.8/src/application.rs:30:13
  57:     0x55a1940b2c11 - sirula::main::ha4487b02ba2824aa
                               at /home/pierrec/Documents/code/sirula/src/main.rs:195:5
  58:     0x55a19407fd3b - core::ops::function::FnOnce::call_once::h6c644d8a0291f292
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  59:     0x55a1940c2c3e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0754c37d9069a377
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:123:18
  60:     0x55a19407ed31 - std::rt::lang_start::{{closure}}::h3ee02f5ba18309dd
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/rt.rs:145:18
  61:     0x55a19438e371 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h268ccd72f86cd1b9
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:259:13
  62:     0x55a19438e371 - std::panicking::try::do_call::ha25d44061134fb07
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  63:     0x55a19438e371 - std::panicking::try::h733e43e42b58f879
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  64:     0x55a19438e371 - std::panic::catch_unwind::h0957b2e138ebf53f
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  65:     0x55a19438e371 - std::rt::lang_start_internal::{{closure}}::hda8d03e070d5de70
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/rt.rs:128:48
  66:     0x55a19438e371 - std::panicking::try::do_call::h3dd1121600870c68
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  67:     0x55a19438e371 - std::panicking::try::h1d0903a55106fd4c
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  68:     0x55a19438e371 - std::panic::catch_unwind::h43a79fd8d8944b59
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  69:     0x55a19438e371 - std::rt::lang_start_internal::h91786933563d435f
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/rt.rs:128:20
  70:     0x55a19407ed00 - std::rt::lang_start::h596524bc7e335d02
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/rt.rs:144:17
  71:     0x55a1940b2c8c - main
  72:     0x7f6a6442db25 - __libc_start_main
  73:     0x55a19407ebfe - _start
  74:                0x0 - <unknown>
  ```

**Comment by DorianRudolph** [comment]
This is very weird. On my system it's also called `org.gnome.Nautilus.desktop` and it works fine.

**Comment by haxibami** [comment]
It seems that desktop entries with `DBusActivatable=true` line fail to start, if `sway` is not configured correctly with `dbus` (&`systemd`?).

Adding this line at the beginning of `~/.config/sway/config` worked fine for me.

```
exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
```

related: [sway wiki](https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start)
