### ISSUE TITLE
Error when trying to use Sirula unless logged in as root

### ISSUE THREAD

**Issue by AtomicJay** [DorianRudolph/sirula#27]
I was getting rid of a bunch of unnecessary files (pictures) when Sirula stopped working. I tried running it from the terminal and got:

```thread 'main' panicked at 'Cannot parse config: {}: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `last_used`", key: [] } }', src/history.rs:18:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

With backtrace:

```thread 'main' panicked at 'Cannot parse config: {}: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `last_used`", key: [] } }', src/history.rs:18:45```
```stack backtrace:```
`   0:     0x558c3dd3e285 - <unknown>`
`   1:     0x558c3dca28bc - <unknown>`
`   2:     0x558c3dd3d574 - <unknown>`
`   3:     0x558c3dd3d2d7 - <unknown>`
`   4:     0x558c3dd55f98 - <unknown>`
`   5:     0x558c3dd55f0c - <unknown>`
`   6:     0x558c3dd55ebd - <unknown>`
`   7:     0x558c3dc77d70 - <unknown>`
`   8:     0x558c3dc780a2 - <unknown>`
`   9:     0x558c3dd25eb7 - <unknown>`
`  10:     0x7fd0a837bf8f - g_closure_invoke`
`  11:     0x7fd0a8397ba8 - <unknown>`
`  12:     0x7fd0a83995c7 - g_signal_emit_valist`
`  13:     0x7fd0a8399824 - g_signal_emit`
`  14:     0x7fd0a8499706 - g_application_register`
`  15:     0x7fd0a849a110 - <unknown>`
`  16:     0x7fd0a849a47a - g_application_run`
`  17:     0x558c3dd2376f - <unknown>`
`  18:     0x558c3dd3b053 - <unknown>`
`  19:     0x558c3dd2297a - <unknown>`
`  20:     0x7fd0a8032310 - __libc_start_call_main`
`  21:     0x7fd0a80323c1 - __libc_start_main@GLIBC_2.2.5`
`  22:     0x558c3dc81265 - <unknown>`
`  23:                0x0 - <unknown>`

However, if I run it while logged in as root, it works fine from the terminal. I've been trying for hours to figure out the problem with no success. I've also tried uninstalling and reinstalling to no avail.

**Comment by AtomicJay** [comment]
After uninstalling I removed all files relating to it, reinstalled it, and it worked after that.
